TEMPLATE      = lib
CONFIG       += plugin c++11
QT           += sql
INCLUDEPATH  += ../../interfaces
LIBS         += -L../../build-static -l$$qtLibraryTarget(interfaces)
HEADERS       = import_module.h
SOURCES       = import_module.cpp
RESOURCES    += resources.qrc
TARGET        = $$qtLibraryTarget(modulo_importar_)
DESTDIR       = ../build-modules
